BrayanBot/BrayanBot

README.md

better `README.md`

---

.dockerignore
Dockerfile
README.md

- added an additional title (because i can)
- a new step to the installation because it felt necessary 
- yarn commands to installation
- initial prep for me writing a wiki with installation/setup steps on linux and windows
**additionally, for the "about" section of github:**
`An extensive, powerful and modular Discord Bot Base written with DiscordJS. Batteries included`

little bit of tidying up & docker

---

Events/ready.js
Modules/Utils/parseSlashCommand.js
Modules/Utils/setupMessage.js
README.md
commands.yml
example.config.yml
install/setup.js
lang.yml
package-lock.json

this marks the point where release 1.0.0 is ready

merge dev branch into main

---

docker-compose.yml

dev: fix Addon_Configs not being bound and rm. tmp

---

Modules/Errors.js
index.js

Displays Errors and keeps bot alive

---

Modules/Utils/setupMessage.js
example.config.yml
install/setup.js

This PR adds more branding options:
- {branding} has been changed to {brand-name}
- Added {brand-logo} for brand/server logo
- Added {brand-link} for brand/server link

More branding options

---

Events/interactionCreate.js

Changes:
Deleted useless permission code
Added support for `AllowedChannels`

Changes in interactionCreate.js

---

Modules/Handlers/ErrorHandler.js

It seems like someone was copying from another bot. I have resolved the issue by putting the correct data in.

ReferenceError: promiseText is not defined

---

Events/ready.js

Updated it so webserver does disable when setting to false.

Webserver not disabling

---

Events/messageCreate.js
Events/ready.js

This PR adds support for adding users to command permissions.
> It's tested and working as intended

Added support for users in permissions

---

.github/CONTRUBUTING.md

Changed links in `CONTRUBUTING.md` from https://github.com/DakshNamdev/BrayanBot to https://github.com/BrayanBotDev/BrayanBot

Links fix in CONTRUBUTING.md

---

Events/messageCreate.js
lang.yml

Fix for "Small" issue with command permission for user.
> Since `userMention` wasn't defined(imported) bot gets error, when It should send NoPermission Embed with user mention.
This PR also contains change in variable(from `{roles}` to `{perms}` since it can be `role` or `user`) + Embed text(From `Allowed Roles` to `Allowed Roles and Users`
This is small, but important PR

Fix User Permission for Command

---

Commands/Admin/eval.js
commands.yml
lang.yml

This PR adds eval command, which allows to run JavaScript code from discord.
It uses User for Permission - Set to `Zorino#1110` by default
All changes has been tested and are working as intended.

New Feature | Eval command

---

README.md

I think this doesn't need any description/info.

Added ElkinSantiana to community devs

---

Events/ready.js
Modules/Handlers/StatusHandler.js
example.config.yml
index.js

This PR adds `StatusHandler` to BrayanBot.
1. Setup with config
2. Rolling status
3. Variables support
4. Variables categories
4.1. Default variables
4.2. Function to add variables

New | StatusHandler

---

Commands/General/serverinfo.js
Modules/Utils.js
lang.yml

This PR moves guildVariables to Utils.js so it can be used by community developers.
It also changes `createdat` to `createdate` in guild variables and in serverinfo embed (for guild and its owner).
All changes are tested and working as intended.

guildVariables + spelling mistakes

---

Events/ready.js

This PR includes #55 code because it was deleted in [this](https://github.com/BrayanBotDev/BrayanBot/commit/1607ac2e5b97353a85e400eb46b04afa6ff5c4ed).

StatusHandler's code in ready.js

---

Commands/General/userinfo.js
Modules/Utils.js
lang.yml

This commit adds UserInfo command + `Utils.memberVariables`
> Every change has been tested and is working as intended

UserInfo + memberVeriables

---

commands.yml

Fix for #60 cuz I'm stoopid and forgot to commit `command.yml` changes when creating `UserInfo` PR.
> Reported by: @xcraftman52

Fix for #60 | Don't ask, ok?

---

Events/ready.js
Modules/Handlers/ExpressHandler.js
WebServer/webserver.yml
index.js

This PR completes webserver config migration started in [this commit](https://github.com/BrayanBot/BrayanBot/commit/65ebd9debf4c1b1aa5223ccd45c536965a83a250). It also changes webserver logs file location to be in WebServer folder.
As always - changes has been tested and are working as intended.

WebServer config code fix

---

Modules/Utils.js

This PR adds Util to find guild with its name/id.
> This PR has been tested and is working as intended

NEW | findGuild() Util
